# Generated by Django 3.2.4 on 2023-11-14 12:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=200)),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Inventory_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=200)),
                ('total_dietary_supplement_items', models.IntegerField(default=1)),
                ('total_quantity_of_each_supplement_item', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(default=0.0)),
                ('date_time_of_purchased', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.customer')),
                ('payment_received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Supplementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement', models.TextField(max_length=255)),
                ('quatity_in_stocked', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('serial_code', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='uploads/dietary/supplement')),
                ('last_date_stocked', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('telephone', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('town', models.TextField(max_length=200)),
                ('adminstrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory_Test_Cost_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.TextField(max_length=200)),
                ('test_cost', models.FloatField(default=0.0)),
                ('serial_code', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OPD_Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital', models.TextField(max_length=200)),
                ('serial_code', models.CharField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Outside_Customers_Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OutsideLabtestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_case_number', models.CharField(max_length=200)),
                ('total_cost', models.FloatField(default=0.0)),
                ('laboratory_report_request_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('laboratory_report_received_status', models.BooleanField(default=False)),
                ('lab_sheet', models.ImageField(upload_to='uploads/outside_lab/')),
                ('report_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.outside_customers_lab_test')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('telephone', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Dietary_Supplementary_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_supplement_request_view', models.BooleanField(default=False)),
                ('dietary_supplement_dispense_viewed', models.BooleanField(default=False)),
                ('total_cost', models.FloatField(default=0.0)),
                ('date_recieved', models.DateField()),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Hospital_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.TextField(max_length=255)),
                ('date_joined', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Laboratory_Test_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test_request_view', models.BooleanField(default=False)),
                ('lab_test_released', models.BooleanField(default=False)),
                ('total_cost', models.FloatField(default=0.0)),
                ('payment_status', models.FloatField(default=0.0)),
                ('date_recieved', models.DateField()),
                ('date_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Medical_Diagnosis_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_complaints', models.CharField(max_length=200)),
                ('doctor_diagnosis', models.CharField(max_length=200)),
                ('in_house_laboratory_test', models.BooleanField(default=True)),
                ('laboratory_report_request_status', models.BooleanField(default=False)),
                ('laboratory_report_received_status', models.BooleanField(default=False)),
                ('dietary_prescription_request', models.BooleanField(default=False)),
                ('dietary_dispensed_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Medical_History_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.TextField(max_length=200)),
                ('checked_in', models.BooleanField(default=False)),
                ('checked_out', models.BooleanField(default=False)),
                ('time_checked_in', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 14, 12, 39, 6, 39161))),
                ('time_checked_out', models.DateTimeField(default=datetime.datetime(2023, 11, 14, 12, 39, 6, 39161))),
                ('opd_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_hospital_history')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.TextField(max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_OPD_Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_history_records')),
                ('vital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.opd_vital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Medical_History_Physician_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_diagnosis_records')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient_medical_diagnosis_records',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_history_records'),
        ),
        migrations.CreateModel(
            name='Patient_Laboratory_Test_Results_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_cost', models.FloatField(default=0.0)),
                ('test_results', models.CharField(default='', max_length=200)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.laboratory_test_cost_details')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_laboratory_test_records')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Laboratory_Test_Records_Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_laboratory_test_records')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient_laboratory_test_records',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_diagnosis_records'),
        ),
        migrations.CreateModel(
            name='Patient_Dietary_Supplementary_Records_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('dietary_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.dietary_supplementary')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_dietary_supplementary_records')),
            ],
        ),
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_diagnosis_records'),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.region'),
        ),
        migrations.CreateModel(
            name='OutsideLabtestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('test_results', models.CharField(max_length=200)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.laboratory_test_cost_details')),
                ('outside_lab_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.outsidelabtestcases')),
            ],
        ),
        migrations.CreateModel(
            name='Out_side_Lab_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_lab_photo', models.ImageField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_medical_diagnosis_records')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory_Test_Cost_Details_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.FloatField(default=0.0)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_laboratory_test_records')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.region'),
        ),
        migrations.CreateModel(
            name='Dietary_Supplementary_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('quantity_stocked', models.IntegerField(default=0)),
                ('date_stocked', models.DateField()),
                ('dietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.dietary_supplementary')),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Supplement_Stocking_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stocked', models.DateField()),
                ('new_quantity_stocked', models.IntegerField()),
                ('old_quantity_stocked', models.IntegerField()),
                ('current_cost', models.FloatField(default=0.0)),
                ('old_cost', models.FloatField(default=0.0)),
                ('quantity_at_the_time_of_stocking', models.IntegerField()),
                ('dietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.dietary_supplementary_details')),
                ('stocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Supplement_Dispenser_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_dietary_supplementary_records')),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Sale_Inventory_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cost_per_unit', models.FloatField(default=0.0)),
                ('dietary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.dietary_supplementary')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Inventory_Records_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0.0)),
                ('quantity_purchased', models.FloatField(default=1)),
                ('total_cost', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.customer_inventory_records')),
                ('dietary_supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.dietary_supplementary')),
            ],
        ),
    ]
