# Generated by Django 4.2.6 on 2024-04-17 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_inventory_records',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer_inventory_records',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer_inventory_records',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient_laboratory_test_records',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patient_laboratory_test_records',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_laboratory_test_records',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 17, 13, 3, 3, 459564)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 13, 3, 3, 459564)),
        ),
    ]
