# Generated by Django 3.2.4 on 2023-11-23 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agadarko_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalCardFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_fees', models.FloatField(verbose_name=0.0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 23, 13, 31, 48, 936763)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 13, 31, 48, 936763)),
        ),
        migrations.CreateModel(
            name='Patient_Hospital_Card_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date_paid', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_hospital_history')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalCardFeesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_charged', models.FloatField(verbose_name=0.0)),
                ('date_changed', models.DateField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card_fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospitalcardfees')),
            ],
        ),
    ]
