# Generated by Django 3.2.4 on 2023-11-24 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0002_auto_20231123_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_hospital_history',
            name='card_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 24, 15, 57, 27, 262415)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 15, 57, 27, 262415)),
        ),
    ]
