# Generated by Django 4.2.6 on 2024-04-18 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0002_customer_inventory_records_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietary_sale_inventory_table',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dietary_sale_inventory_table',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dietary_sale_inventory_table',
            name='discount_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 1, 13, 2, 890248)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 1, 13, 2, 890248)),
        ),
    ]
