# Generated by Django 4.2.6 on 2024-04-18 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0003_dietary_sale_inventory_table_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietary_sale_inventory_table',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='dietary_sale_inventory_table',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='dietary_sale_inventory_table',
            name='discount_status',
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 18, 1, 18, 28, 139492)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 1, 18, 28, 139492)),
        ),
    ]
