# Generated by Django 5.0.4 on 2024-04-22 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0004_remove_dietary_sale_inventory_table_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_inventory_records',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 22, 6, 17, 2, 199155)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 6, 17, 2, 199155)),
        ),
    ]
