# Generated by Django 3.2.4 on 2023-12-03 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0004_auto_20231130_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patient_dietary_supplementary_records',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 3, 18, 59, 22, 194351)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 18, 59, 22, 194351)),
        ),
    ]
