# Generated by Django 3.2.4 on 2023-12-03 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0005_auto_20231203_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_dietary_supplementary_records_details',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 3, 20, 15, 52, 955089)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 20, 15, 52, 955089)),
        ),
    ]
