# Generated by Django 3.2.4 on 2023-12-03 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0006_auto_20231203_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 3, 20, 16, 10, 195176)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 20, 16, 10, 195176)),
        ),
    ]
