# Generated by Django 3.2.4 on 2023-12-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0007_auto_20231203_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietary_sale_inventory_table',
            name='date_purschaesd',
            field=models.DateField(default='1990-08-04'),
        ),
        migrations.AddField(
            model_name='dietary_sale_inventory_table',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 22, 13, 30, 9, 155047)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 13, 30, 9, 155047)),
        ),
    ]
