# Generated by Django 3.2.4 on 2023-12-27 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadarko_v2', '0008_auto_20231222_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_inventory_records',
            name='date_time_of_purchased',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 21, 57, 38, 621357)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 21, 57, 38, 621357)),
        ),
    ]
