# Generated by Django 3.2.4 on 2024-03-15 05:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agadarko_v2', '0009_auto_20231227_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalCardRenewalFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_renewal_fees', models.FloatField(verbose_name=0.0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospital')),
            ],
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 15, 5, 52, 59, 104716)),
        ),
        migrations.AlterField(
            model_name='patient_medical_history_records',
            name='time_checked_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 5, 52, 59, 104716)),
        ),
        migrations.CreateModel(
            name='Patient_Hospital_Card_Renewal_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('date_paid', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_hospital_history')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Out_side_Lab_test_Result_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_results', models.CharField(default='', max_length=200)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.laboratory_test_cost_details')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.patient_laboratory_test_records')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalCardRenewalFeesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_charged', models.FloatField(verbose_name=0.0)),
                ('date_changed', models.DateField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card_fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agadarko_v2.hospitalcardrenewalfees')),
            ],
        ),
    ]
